In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("./bit_byte_tree.csv")

In [5]:
df.head()

                      byte                         bit
0  michelle hwang(mhwangc)  austin patel(austinapatel)
1  michelle hwang(mhwangc)   henry muller(henrymuller)
2  michelle hwang(mhwangc)           brian yu(bri25yu)
3      matthew owen(mowen)  austin patel(austinapatel)
4      matthew owen(mowen)   henry muller(henrymuller)

In [20]:
byte = "christy huang"
df[df['byte'].str.contains(byte, case=False, na=False)]

                             byte                            bit
1004  christy huang(christyhuang)      jeffrey gong(jeffreygong)
1005  christy huang(christyhuang)      aditi mundra(aditimundra)
1006  christy huang(christyhuang)  dylan anuskiewicz(dylana2z05)

In [21]:
bit = "jeffrey gong"
df[df['bit'].str.contains(bit, case=False, na=False)]

                                byte                        bit
1004     christy huang(christyhuang)  jeffrey gong(jeffreygong)
1007  michelle park(michelle.taeeun)  jeffrey gong(jeffreygong)